### ISSUE TITLE
Documentation of API?

### ISSUE THREAD

**Issue by CAYdenberg** [lyonlai/bootstrap-paginator#21]
The original website (bootstrappaginator.org) for this project is down, and the documentation on this branch hasn't been updated in some time.

I'm having compatibility issues trying to upgrade to Bootstrap v3, and it's hard to know where things are going wrong.

Can anyone help me with the following code?

```
//now change .pagination
var options = {
    currentPage: currentPage,
    totalPages: totalPages,
    onPageClicked: function(e, originalEvent, type, page) {
      switchPage(page);
    }
};
$('.pagination').bootstrapPaginator(options);
```

**Comment by peterblazejewicz** [comment]
@CAYdenberg 
The paginator requires additional option for v.3:

``` JavaScript
bootstrapMajorVersion: 3
```

Try with that option :)

**Comment by jmshal** [comment]
Feel free to access the documentation directly via gh-pages (http://lyonlai.github.io/bootstrap-paginator/).

**Comment by CAYdenberg** [comment]
Thank you both. Got it working.
